### ISSUE TITLE
家宽ipv6前缀会变，取消光猫RA广播会造成断网

### ISSUE THREAD

**Issue by adrianzhang** [dnomd343/XProxy#13]
如果取消光猫的RA，怎么获得变化后的前缀？

**Comment by dnomd343** [comment]
旁路由代理IPv6比较麻烦，主要是IPv6没有DHCP分配网关的概念，而是设备接入时组播RS请求，路由器响应RA消息（并定时组播），设备收到RA消息后会将消息来源认定为IPv6网关，所以根本问题在于RA发送源不可控。

由于旁路由的拓扑结构，代理设备和ISP设备处于同个局域网下，NDP协议均可达，这导致流量“牵引”到旁路由比较麻烦。目前较为合适的方法如下：

1. 更新拓扑结构，让代理路由前置直接接管V6流量，这样子就无需考虑双RA广播问题了。
2. 关闭光猫RA广播，在旁路由上部署定时脚本，通过http请求光猫管理页获取分配的IPv6前缀，并在更新时应用到radvd的配置文件中，这个方式不太优雅但很实用。
3. 配置RA广播优先级，radvd提供了AdvDefaultPreference字段，可以指定更高的优先级，这个字段是RA消息的可选项，ISP光猫一般不会发送，可以通过这个消息叠加，但需要接入设备支持。

**Comment by adrianzhang** [comment]
> 旁路由代理IPv6比较麻烦，主要是IPv6没有DHCP分配网关的概念，而是设备接入时组播RS请求，路由器响应RA消息（并定时组播），设备收到RA消息后会将消息来源认定为IPv6网关，所以根本问题在于RA发送源不可控。
> 
> 由于旁路由的拓扑结构，代理设备和ISP设备处于同个局域网下，NDP协议均可达，这导致流量“牵引”到旁路由比较麻烦。目前较为合适的方法如下：
> 
> 1. 更新拓扑结构，让代理路由前置直接接管V6流量，这样子就无需考虑双RA广播问题了。
> 2. 关闭光猫RA广播，在旁路由上部署定时脚本，通过http请求光猫管理页获取分配的IPv6前缀，并在更新时应用到radvd的配置文件中，这个方式不太优雅但很实用。
> 3. 配置RA广播优先级，radvd提供了AdvDefaultPreference字段，可以指定更高的优先级，这个字段是RA消息的可选项，ISP光猫一般不会发送，可以通过这个消息叠加，但需要接入设备支持。

谢谢！方法3能解决问题。
