### ISSUE TITLE
关于DNS（域名解析）的疑惑

### ISSUE THREAD

**Issue by qswyer** [dnomd343/XProxy#14]
针对XProxy & cleardns，有一些疑惑，还请指教。

配置情况：
1、XProxy和cleardns均运行在局域网设备上，其IP地址分别为192.168.2.2和192.168.2.3（路由器的IP地址为192.168.2.1）
2、outbounds配置了vmess + TCP + TLS，其中vmess的address是一个域名example.com
3、routing配置了国内国外分流

针对以上配置进行的测试及结果如下：
a、将xproxy.yml中dns配置为阿里云的DNS地址223.5.5.5，访问国外网站正常；
b、将xproxy.yml中dns配置为自建的cleardns地址192.168.2.3，访问国外网站不通，查看xray的日志发现有以下输出：dial tcp: lookup example.com on 192.168.2.3:53 no such host。登录xproxy和cleardns容器使用nslookup均可以解析出域名example.com的IP地址（应该是套了CDN的缘故，域名对应的IP是Cloudflare地址188.114.97.3）

阅读了XProxy项目源码，xproxy.yml中dns会配置到/etc/resolv.conf中。依照我的理解，若xray中未配置DNS相关的参数，则使用系统内置的DNS配置，因此这个问题应该是cleardns的功能有问题？还请不吝赐教。

**Comment by dnomd343** [comment]
从现状看，192.168.2.2和192.168.2.3均可以正常访问外网，但看起来无法从192.168.2.2访问到192.168.2.3。

这个DNS参数指定的是XProxy容器的系统默认DNS地址，也就是Xray默认使用的地址，这里配置为192.168.2.3即系统默认DNS被设置为cleardns的容器。

从Xray的日志看，无法解析到应该是cleardns本身有问题，我们可以按以下步骤排查：
1. 在192.168.2.2的容器中，尝试ping到192.168.2.3，通过则下一步。
2. 在192.168.2.3的容器中，使用dig查询本地DNS，即 `dig baidu.com @127.0.0.1 -p 53` 命令，如果返回则下一步。
3. 在192.168.2.2的容器中，执行 `dig baidu.com @192.168.2.3 -p 53` 命令，确认是否可以查到DNS地址。

**Comment by qswyer** [comment]
感谢指点，确实是cleardns本身的问题，已经解决了。
