### ISSUE TITLE
请问是否支持非docker部署

### ISSUE THREAD

**Issue by fo2w** [dnomd343/XProxy#4]
**背景**
宿主机是群晖, 不想动群晖的网卡参数
几乎将docker里的东西在群晖虚拟机里部署了一遍, 当然macvlan和混杂模式没有设置

**复现步骤**
log级别调整为debug, 分别在
机器A: xproxy部署的虚拟机
机器B: 群晖
上执行
nslookup xxx xproxyIP
curl xxx
等操作

**遇到的问题**
nslookup正常(含墙内/外域名)
nslookup xxx xproxyIP
正常(含墙内/外域名)
curl xxx
墙内域名正常
curl xxx
墙外域名一直卡在连接中
观察xproxy/xray log, 看起来流量没有进来

**Comment by dnomd343** [comment]
非虚拟机部署的话理论上可以跑，但是 XProxy 本身不会去分析主机网络，也就是 iptables 以及各种路由规则，这在 Docker 中可以正常工作，但是直接放宿主机可能会有意想不到的后果。

对于宿主机直接工作，我更建议使用 [v2rayA](https://github.com/v2rayA/v2rayA.git) 项目。

**Comment by fo2w** [comment]
其实v2rayA我也考察过一段时间, 在虚拟机直接跑也会有很多奇奇怪怪的问题, 总之谢谢回复, 辛苦了
