### ISSUE TITLE
容器路径`/release`路径问题

### ISSUE THREAD

**Issue by aoleou** [dnomd343/XProxy#6]
大神,请教一下,docker hub 上的容器,启动起来没有`/release/...`这个前缀的路径.
![image](https://github.com/dnomd343/XProxy/assets/124496859/6c8e7fef-9486-44cb-b6df-4094a4b58a17)
为什么下方源码里面有这个前缀呢? 是docker hub 上的镜像不是下面的Dockerfile构建的吗?
https://github.com/dnomd343/XProxy/blob/a9b16879181a4013b126f686276579c79962c8be/Dockerfile#L33

**Comment by dnomd343** [comment]
镜像是基于项目Dockerfile构建的，这个目录是Docker[分段构建](https://docs.docker.com/build/building/multi-stage/)的中间产物，用于优化体积和构建流程，并不会释放到最终镜像中。

```
...

--- 下面是 release 层 ---

FROM ${ALPINE} AS release
...
COPY --from=xproxy /xproxy /release/usr/bin/
COPY --from=assets /assets.tar.xz /release/
COPY --from=xray /xray /release/usr/bin/
...

--- 下面是最终层 ---

FROM ${ALPINE}
...
COPY --from=release /release/ /
...
```

构建逻辑如上，你可以把 `release` 理解为一个临时层，它将 `xproxy` / `assets` / `xray` 这三个临时层的文件收集到 `/release/` 目录下，再将它复制到最终镜像的根目录下。

例如来自 `xray` 镜像的 `/xray` 文件，将被复制为 `release` 层的 `/release/usr/bin/xray` ，再复制为最终镜像的 `/usr/bin/xray` 文件。

**Comment by aoleou** [comment]
首先, **[手动作揖 + 抱拳].jpg**. 感谢大神回复.

分段构建这个知识点,我明白一些了. 然后在实操的时候, 比如我不想下载go的依赖, 不想花时间在构建容器的时候构建xray和XProxy上. 

也就是说,我的需求是,我修改了XProxy的源码以后,我在本机build好.然后通过以下脚本:
```sh
go build -o xproxy -v -trimpath -ldflags "-X main.version=$(git describe --tag) -s -w" ./cmd
scp /data/XProxy/xproxy ripper@192.168.0.67:/data/XProxy
```
将`xproxy`可执行文件上传到 https://github.com/XTLS/Xray-core/discussions/2872#discussion-6010475 这里的 **电脑B** :
```txt
环境：
电脑A：windows， ip： 192.168.0.66；
电脑B：linux， ip： 192.168.0.67;
电脑C(服务器):vps ip: yourvpsip
```
然后直接在电脑B上build出容器. 因为没有下载的环节,就会很丝滑.

<br />
<br />

其中, 电脑B的Dockerfile所在的目录内容为:
```txt
/data/XProxy/
├── Dockerfile
......
├── geoip.dat
├── geosite.dat
├── xproxy # xproxy 可执行文件
└── xray # xray  可执行文件
```
build和run容器的命令为:
```sh
docker build -t xproxy:2 -f /data/www/XProxy/Dockerfile .
docker run --restart always \
                              --privileged --network macvlan -dt \
                              --name route1 --hostname route \
                              --volume /etc/route/:/xproxy/ \
                              --volume /etc/timezone:/etc/timezone:ro \
                              --volume /etc/localtime:/etc/localtime:ro \
                              --ip 192.168.0.3 \
                              xproxy:2
```
**现在我遇到的问题是:**

```sh
ARG ALPINE="alpine:3.18"
ARG GOLANG="golang:1.21-alpine3.18"

FROM ${GOLANG} AS xray
WORKDIR /output/
COPY xray /output/

FROM ${GOLANG} AS xproxy
WORKDIR /output/
COPY xproxy /output/

FROM ${ALPINE} AS assets
RUN apk add xz
WORKDIR /output
COPY geoip.dat /output/
COPY geosite.dat /output/
RUN tar cJf /output/assets.tar.xz /output/geoip.dat /output/geosite.dat

FROM ${ALPINE} AS release
RUN apk add upx
WORKDIR /release/run/radvd/
WORKDIR /release/var/lib/dhcp/
RUN touch dhcpd.leases dhcpd6.leases
COPY --from=xproxy /output /release/usr/bin/
COPY --from=assets /output/assets.tar.xz /release/
COPY --from=xray /output /release/usr/bin/
WORKDIR /release/usr/bin/
RUN ls | xargs -n1 -P0 upx -9

FROM ${ALPINE} AS final
WORKDIR /xproxy/
RUN apk add --no-cache dhcp radvd iptables ip6tables
COPY --from=release /release/ /

ENTRYPOINT ["xproxy"]
```
第一: 为什么上面的脚本构建出来的容器  `STATUS Restarting (127) Less than a second ago` 一直在重启. 然后 `docker logs route1` 还没有任何输出. 对此感到很是困惑. 

第二: 就是大神,你在本地开发的时候,也是像我这样test程序结果的吗?还是直接在本地test, 方便分享一下是怎么test和部署程序的吗?

以上疑惑, 麻烦大神有空帮忙看一下了, 非常感谢哈~

**Comment by dnomd343** [comment]
如果资源文件都在本地，Dockerfile 文件可以直接简写，upx 部分可以去掉（upx 用于让 BIN 体积更小，但会在 RAM 匿名页吃回来，这里不影响使用），改完的文件例子如下。

```
ARG ALPINE="alpine:3.18"

FROM ${ALPINE} AS release
WORKDIR /release/run/radvd/
WORKDIR /release/var/lib/dhcp/
RUN touch dhcpd.leases dhcpd6.leases
COPY ./xproxy /release/usr/bin/
COPY ./assets.tar.xz /release/
COPY ./xray /release/usr/bin/

FROM ${ALPINE}
RUN apk add --no-cache dhcp radvd iptables ip6tables
COPY --from=release /release/ /
WORKDIR /xproxy/
ENTRYPOINT ["xproxy"]
```

构建的时候，建议不要用 `-f` 指定绝对路径，镜像构建存在上下文，这里的上下文目录就是 `/data/XProxy/` ，构建的例子如下。

```bash
> cd /data/XProxy/
> docker build -t xproxy:2 .
```

注意这里需要给 `xray` 和 `xproxy` 文件添加可执行属性，即 `chmod +x xray xproxy` ，你的容器异常退出应当就是这个导致的。

如果仍然无法启动，去除掉 daemon 参数可以直接在命令行观察到容器启动行为，例如下面的命令。

```bash
docker run --restart always \
  --privileged --network macvlan --rm -it \
  --name route1 --hostname route \
  --volume /etc/route/:/xproxy/ \
  --volume /etc/timezone:/etc/timezone:ro \
  --volume /etc/localtime:/etc/localtime:ro \
  --ip 192.168.0.3 \
  xproxy:2
```

**Comment by dnomd343** [comment]
开发是基于 devcontainer 工作流，重点是在语言实现逻辑部分，这些由单测来 cover 就行，不会在真实的内网设备上跑。

网络相关功能和命令是预先在真机上调通，再把逻辑写回到代码里面，后续再到网络设备上测试。
